RENKO:
  BRICK_SIZE: 5
SUPERTREND:
  PERIOD: 10
  MULTIPLIER: 2.0
MARKET_HOURS:
  START_TIME: 09:15
  END_TIME: '15:30'
  TOTAL_MINUTES: 375
TRADING_DAYS:
- '2025-10-15'
- '2025-10-16'
- '2025-10-17'
- '2025-10-23'
- '2025-10-24'
- '2025-10-27'
- '2025-10-29'
- '2025-10-30'
- '2025-10-31'
OUTPUT:
  GENERATE_PLOTS: false
