INDICATORS:
  SUPERTREND1:
    ATR_LENGTH: 10
    FACTOR: 2
  SWING_LOW:
    CANDLES: 5
  WPR_FAST_LENGTH: 9
  WPR_SLOW_LENGTH: 28
  STOCH_RSI:
    K: 3
    D: 3
    RSI_LENGTH: 14
    STOCH_PERIOD: 14
  DEMARKER:
    PERIOD: 14
    OB_LEVEL: 0.7
    OS_LEVEL: 0.3
  FAST_MA:
    MA: sma
    LENGTH: 11
  SLOW_MA:
    MA: sma
    LENGTH: 13
THRESHOLDS:
  WPR_FAST_OVERSOLD: -79
  WPR_SLOW_OVERSOLD: -77
  STOCH_RSI_OVERSOLD: 20
  DEMARKER_OVERBOUGHT: 0.7
  DEMARKER_OVERSOLD: 0.3
TARGET_EXPIRY:
  EXPIRY_WEEK_LABELS:
  - OCT20
  - OCT28
  - NOV04
  - NOV11
  - NOV18
  - NOV25
  - DEC02
  - DEC09
  - DEC16
  - JAN13
  - JAN20
  - JAN27
  - FEB03
  TRADING_DAYS:
  - '2026-01-13'
  - '2026-01-20'
  - '2026-01-27'
  - '2026-02-03' 
PATHS:
  DATA_DIR: data
  LOGS_DIR: logs
MARKET_HOURS:
  START_TIME: 09:15
  END_TIME: '15:14'
  TOTAL_MINUTES: 359
CPR_MARKET_SENTIMENT_VERSION: v2
ENABLE_SENTIMENT_PROCESSING: false
STRIKE_TYPE_PROCESSING:
  ATM: true
  OTM: true
