INDICATORS:
  SUPERTREND1:
    ATR_LENGTH: 10
    FACTOR: 2.5
  SWING_LOW:
    CANDLES: 5
  WPR_FAST_LENGTH: 9
  WPR_SLOW_LENGTH: 28
  STOCH_RSI:
    K: 3
    D: 3
    RSI_LENGTH: 14
    STOCH_PERIOD: 14
  DEMARKER:
    PERIOD: 14
    OB_LEVEL: 0.7
    OS_LEVEL: 0.3
  FAST_MA:
    MA: sma
    LENGTH: 11
  SLOW_MA:
    MA: sma
    LENGTH: 13
THRESHOLDS:
  WPR_FAST_OVERSOLD: -79
  WPR_SLOW_OVERSOLD: -77
  STOCH_RSI_OVERSOLD: 20
  DEMARKER_OVERBOUGHT: 0.7
  DEMARKER_OVERSOLD: 0.3
TARGET_EXPIRY:
  EXPIRY_WEEK_LABELS:
  - OCT20
  - OCT28
  - NOV04
  - NOV11
  - NOV18
  - NOV25
  - DEC02
  - DEC09
  - DEC16
  - DEC23
  - DEC30
  - JAN06
  - JAN13
  - JAN20
  - JAN27
  - FEB03
  - FEB10
  - FEB17
  TRADING_DAYS:
  # - '2025-10-15'
  # - '2025-10-16'
  # - '2025-10-17'
  # - '2025-10-27'
  # - '2025-10-31'
  # - '2025-11-06'
  # - '2025-11-07'
  # - '2025-11-10'
  # - '2025-11-14'
  # - '2025-11-17'
  # - '2025-11-19'
  # - '2025-11-20'
  # - '2025-11-21'
  # - '2025-11-24'
  # - '2025-11-26'
  # - '2025-12-03'
  # - '2025-12-11'
  # - '2025-12-15'

  # - '2026-01-16'
  # - '2026-01-19'
  # - '2026-01-22'

  # - '2026-01-28'
  # - '2026-01-29'

  # - '2025-10-23'
  # - '2025-10-29'
  # - '2025-10-30'
  # - '2025-11-13'
  # - '2025-11-28'
  # - '2025-12-01'
  # - '2025-12-04'
  # - '2025-12-05'
  # - '2025-12-10'
  # - '2026-01-07'
  # - '2026-01-08'
  # - '2026-01-14'
  # - '2026-01-23'
  # - '2026-02-01'

  # - '2025-10-24'
  # - '2025-11-03'
  # - '2025-11-12'
  # - '2025-11-27'
  # - '2025-12-08'
  # - '2025-12-12'
  # - '2026-01-09'
  # - '2026-01-12'
  # - '2026-01-21'
  # - '2026-01-30'
  # - '2026-02-02'
  # - '2026-02-04'
  # - '2026-02-05'  
  # - '2026-02-06'
  # - '2026-02-09'
  - '2026-02-11'

PATHS:
  DATA_DIR: data
  LOGS_DIR: logs
MARKET_HOURS:
  START_TIME: 09:15
  END_TIME: '15:14'
  TOTAL_MINUTES: 359
CPR_MARKET_SENTIMENT_VERSION: v2
ENABLE_SENTIMENT_PROCESSING: false
STRIKE_TYPE_PROCESSING:
  ATM: true
  OTM: true
