INDICATORS:
  SUPERTREND:
    ATR_LENGTH: 10
    FACTOR: 2
  WPR_FAST_LENGTH: 9
  WPR_SLOW_LENGTH: 28
  STOCH_RSI:
    K: 3
    D: 3
    RSI_LENGTH: 14
    STOCH_PERIOD: 14
  FAST_MA:
    MA: ema
    LENGTH: 3
  SLOW_MA:
    MA: sma
    LENGTH: 7
TARGET_EXPIRY:
  EXPIRY_WEEK_LABELS:
  - OCT20
  - OCT28
  - NOV04
  - NOV11
  TRADING_DAYS:
  - '2025-10-15'
  - '2025-10-16'
  - '2025-10-17'
  - '2025-10-23'
  - '2025-10-24'
  - '2025-10-27'
  - '2025-10-29'
  - '2025-10-30'
  - '2025-10-31'
  - '2025-11-03'
  - '2025-11-06'
  - '2025-11-07'
  - '2025-11-10'
PATHS:
  DATA_DIR: data
  LOGS_DIR: logs
MARKET_HOURS:
  START_TIME: 09:15
  END_TIME: '15:14'
  TOTAL_MINUTES: 359
